---

- name: GET STRUCTURED DATA BACK FROM CLI DEVICES
  hosts: ios
  connection: local
  gather_facts: False

  tasks:

  - name: OBTAIN LOGIN CREDENTIALS
    include_vars: secrets.yaml

  - name: DEFINE PROVIDER
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}" 

  - name: GET SH IP INT BRIEF
    ntc_show_command:
      connection: ssh
      template_dir: /home/runmosta/project/Ansible/ntc-templates/templates
      platform: cisco_ios
      command: 'show inventory'
      username: "{{ provider.username }}"
      password: "{{ provider.password }}"
      host: "{{ inventory_hostname }}"
    register: result

  -  copy:  
      content: "{{ result }}"
      dest: "Inventory/{{ inventory_hostname }}_ios_inven.json"
