---
- gather_facts: false
  hosts: ios
  connection: local
  
  roles:
    - router

  tasks:
  - name: OBTAIN LOGIN CREDENTIALS
    include_vars: secrets.yaml
 
  - name: DEFINE PROVIDER
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: SET SCRIPT CONFIG
    ios_config:
      provider: "{{ provider }}"
      src: "~/project/Ansible/CFGS/{{inventory_hostname}}.cfg"
    register: output
  - debug: var=output 
#  - name: BUILD CONFIGS
#      template:
#        src: vlans.j2
#        dest: configs/vlans.cfg
#
#  - name: ENSURE VLANS EXIST
#      ios_config:
#        src: configs/vlans.cfg
#        provider: "{{ provider }}"