-  name: "REMOVE NTP SOURCE"
   when: "(ntp_source is not defined) and (get_ntp_config.stdout_lines[2][0] != \"\")"
   register: remove_ntp_source
   ios_config: 
    provider: "{{ provider }}"
    lines: 
      - "no {{ get_ntp_config.stdout_lines[2][0] }}"
- name: "POSTPONE CONFIGURATION SAVE"
  when: "(remove_ntp_source.changed == true)"
  set_fact: configured=true