---
- name: "REMOVE SUMMERTIME"
  when: "(summertime is not defined) and (get_ntp_config.stdout_lines[1][0] != \"\")"
  register: remove_summertime
  ios_config: 
    provider: "{{ provider }}"
    lines: 
      - "no {{ get_ntp_config.stdout_lines[1][0] }}"
- name: "POSTPONE CONFIGURATION SAVE"
  when: "(remove_summertime.changed == true)"
  set_fact: configured=true